In [6]:
import numpy as np

In [2]:
# pip install numpy - if running on console
# !pip install numpy - if running in jupyter notebook

In [3]:
np.__version__

'1.15.0'

In [9]:
! pip install --upgrade numpy 

Requirement already up-to-date: numpy in c:\anaconda3\lib\site-packages (1.15.0)


distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [4]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


### Np Zeros

In [8]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a =np.zeros((3,2))

In [19]:
a.shape

(3, 2)

In [26]:
a.size

6

In [20]:
a[1,1]

0.0

In [21]:
a[1,1] = 5

In [22]:
a

array([[0., 0.],
       [0., 5.],
       [0., 0.]])

In [27]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [39]:
Z = np.arange(10, 50, 2)

In [40]:
Z = Z[::-1]

In [41]:
Z

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

In [42]:
Z

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

In [43]:
Z.shape

(20,)

In [46]:
Z.reshape((5,4))

array([[48, 46, 44, 42],
       [40, 38, 36, 34],
       [32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10]])

In [48]:
Z = Z.reshape((4,5))

In [49]:
Z

array([[48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30],
       [28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10]])

In [51]:
b = np.array([1,6,3,0,5,0,4,0,3,0])

In [52]:
type(b)

numpy.ndarray

In [53]:
c = [1,2,3,4,5,6]

In [54]:
c = np.array(c)

In [55]:
type(c)

numpy.ndarray

In [56]:
b

array([1, 6, 3, 0, 5, 0, 4, 0, 3, 0])

In [61]:
np.nonzero(b)

(array([0, 1, 2, 4, 6, 8], dtype=int64),)

In [63]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.random.random((3,3))

array([[0.14780643, 0.97313017, 0.47465556],
       [0.76927236, 0.35098743, 0.60199625],
       [0.62598645, 0.91727249, 0.71405053]])

In [70]:
Y = np.random.random(9).reshape(3,3)

In [71]:
Y

array([[0.5772286 , 0.8132489 , 0.01456975],
       [0.73026581, 0.35751358, 0.04384381],
       [0.28753297, 0.88640958, 0.95151788]])

In [73]:
Y.max()

0.9515178807716016

In [74]:
Y.min()

0.014569751698679356

In [75]:
Y.mean()

0.5180145427411492

In [76]:
Y.sum()

4.662130884670343

In [77]:
Y.std()

0.336078221894124