In [1]:
import numpy as np

In [6]:
np.random.random(4)

array([0.35295753, 0.03481008, 0.47078859, 0.12612831])

In [15]:
np.random.randint(10, 100, (7))

array([82, 82, 30, 14, 43, 62, 61])

In [9]:
a = np.random.randint(10, 100, (7))

In [10]:
a.mean()

46.42857142857143

In [11]:
a

array([59, 24, 89, 16, 39, 81, 17])

In [12]:
a.std()

28.070610675107684

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.nan * 0

nan

In [19]:
np.NAN

nan

In [28]:
Z = np.zeros((8,8))

In [30]:
Z[1::2, ::2] = 1
#Z[::2, 1::2] = 1

In [31]:
Z

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [42]:
np.diag(1 + np.arange(4), k=3)

array([[0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [43]:
1 + np.arange(4)

array([1, 2, 3, 4])

In [46]:
Z = np.ones((8,8), dtype=int)
Z[1::2, ::2] = 0
Z[::2, 1::2] = 0

In [47]:
Z

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [53]:
a = np.ones((5,3)) 
b = np.ones((3,2))

In [54]:
np.dot(a, b)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [81]:
X = np.arange(11)

In [82]:
X[(X>=3) & (X<=6)] = 0
X

array([ 0,  1,  2,  0,  0,  0,  0,  7,  8,  9, 10])

In [87]:
X[3:7] = -1* np.arange(start=3,stop=7)

In [86]:
X

array([ 0,  1,  2, -3, -4, -5, -6,  7,  8,  9, 10])

In [67]:
Y = np.arange(11)
Y[(Y>=3) & (Y<=6)] = -1 * Y[(Y>=3) & (Y<=6)]

In [68]:
Y

array([ 0,  1,  2, -3, -4, -5, -6,  7,  8,  9, 10])

In [70]:
Y = np.arange(11)
Y[(Y>=3) & (Y<=6)] *= -1

In [71]:
Y

array([ 0,  1,  2, -3, -4, -5, -6,  7,  8,  9, 10])

In [72]:
sum(Y)

19

In [73]:
Y.sum()

19

In [80]:
int(np.floor(3.45))

3

In [76]:
np.ceil(3.10)

4.0

In [77]:
np.round(3.4)

3.0

In [93]:
np.linspace(0,100, endpoint=False)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.,
       52., 54., 56., 58., 60., 62., 64., 66., 68., 70., 72., 74., 76.,
       78., 80., 82., 84., 86., 88., 90., 92., 94., 96., 98.])

In [96]:
np.linspace(0,10, 5,endpoint=False)

array([0., 2., 4., 6., 8.])

In [98]:
A = np.random.randint(0,2,5)

In [100]:
B = np.random.randint(0,2,5)

In [101]:
A, B

(array([0, 1, 0, 0, 1]), array([0, 1, 1, 0, 1]))

In [102]:
np.allclose(A, B)

False

In [110]:
A_ = np.array([0,1,0,1,0])

In [111]:
np.allclose(A, A_)

False

In [105]:
np.sqrt(64)

8.0

In [124]:
C = np.random.randint(10, 45,10)

In [125]:
C

array([22, 41, 44, 34, 42, 21, 23, 36, 21, 19])

In [126]:
C.argmax()

2

In [127]:
np.argmax(C)

2

In [128]:
C.argsort()

array([9, 5, 8, 0, 6, 3, 7, 1, 4, 2], dtype=int64)

In [129]:
C

array([22, 41, 44, 34, 42, 21, 23, 36, 21, 19])

In [130]:
C.sort()

In [131]:
C

array([19, 21, 21, 22, 23, 34, 36, 41, 42, 44])

In [132]:
C.argsort()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [133]:
np.abs(-19)

19

In [136]:
F = np.arange(10, dtype=np.int32)

In [137]:
F

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
F = F.astype(np.float32, copy=False)

In [139]:
F

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [140]:
a = [1,2]
b = a
b.append(3)

In [141]:
a

[1, 2, 3]

In [143]:
np.random.uniform(1,2,10)

array([1.40979127, 1.23254282, 1.40873814, 1.2880905 , 1.20437671,
       1.10548883, 1.85140948, 1.38079265, 1.85444389, 1.61413297])

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)