In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
x1 = 3
x2 = 2
y1 = 17

x3 = 2
x4 = 3
y2 = 18

In [5]:
x = np.array([[3,2],
             [2,3]])

In [6]:
y = np.array([[17],
              [18]])

In [7]:
x

array([[3, 2],
       [2, 3]])

In [8]:
y

array([[17],
       [18]])

In [15]:
w = np.array([np.random.randn(1),
    np.random.randn(1)])

In [16]:
w

array([[-0.08265759],
       [ 0.29231501]])

In [17]:
x.shape, y.shape, w.shape

((2, 2), (2, 1), (2, 1))

In [23]:
lr = 0.01
w1 = 10
w2 = 5

w = np.array([[w1],
              [w2]])
for i in range(200):
    y_pred = np.dot(x, w)
    error = 0.5*np.sum((y-y_pred)**2)
    dEw1 = 2 * np.dot(((y-y_pred).T), -x[:,0])
    dEw2 = 2 * np.dot(((y-y_pred).T), -x[:,1])
    w1 = w1 - lr * dEw1
    w2 = w2 - lr * dEw2
    w = np.array([[w1][0],
                [w2][0]])
    print("Value of w1 - ", w[0], " and w2 - ", w[1])

Value of w1 -  [7.94]  and w2 -  [3.06]
Value of w1 -  [6.8812]  and w2 -  [2.1188]
Value of w1 -  [6.323576]  and w2 -  [1.676424]
Value of w1 -  [6.01710448]  and w2 -  [1.48289552]
Value of w1 -  [5.83676239]  and w2 -  [1.41323761]
Value of w1 -  [5.72002714]  and w2 -  [1.40497286]
Value of w1 -  [5.6356266]  and w2 -  [1.4268734]
Value of w1 -  [5.56791407]  and w2 -  [1.46333593]
Value of w1 -  [5.50905579]  and w2 -  [1.50656921]
Value of w1 -  [5.45512467]  and w2 -  [1.55268783]
Value of w1 -  [5.40414718]  and w2 -  [1.59975907]
Value of w1 -  [5.35512673]  and w2 -  [1.64682639]
Value of w1 -  [5.30755545]  and w2 -  [1.69342111]
Value of w1 -  [5.26116997]  and w2 -  [1.73931832]
Value of w1 -  [5.21582938]  and w2 -  [1.78441476]
Value of w1 -  [5.1714542]  and w2 -  [1.82866787]
Value of w1 -  [5.12799582]  and w2 -  [1.87206522]
Value of w1 -  [5.08542125]  and w2 -  [1.91460927]
Value of w1 -  [5.0437055]  and w2 -  [1.95630976]
Value of w1 -  [5.00282773]  and w2 -  [

Value of w1 -  [3.08568614]  and w2 -  [3.91431386]
Value of w1 -  [3.08397242]  and w2 -  [3.91602758]
Value of w1 -  [3.08229297]  and w2 -  [3.91770703]
Value of w1 -  [3.08064711]  and w2 -  [3.91935289]
Value of w1 -  [3.07903417]  and w2 -  [3.92096583]
Value of w1 -  [3.07745348]  and w2 -  [3.92254652]
Value of w1 -  [3.07590441]  and w2 -  [3.92409559]
Value of w1 -  [3.07438633]  and w2 -  [3.92561367]
Value of w1 -  [3.0728986]  and w2 -  [3.9271014]
Value of w1 -  [3.07144063]  and w2 -  [3.92855937]
Value of w1 -  [3.07001181]  and w2 -  [3.92998819]
Value of w1 -  [3.06861158]  and w2 -  [3.93138842]
Value of w1 -  [3.06723935]  and w2 -  [3.93276065]
Value of w1 -  [3.06589456]  and w2 -  [3.93410544]
Value of w1 -  [3.06457667]  and w2 -  [3.93542333]
Value of w1 -  [3.06328514]  and w2 -  [3.93671486]
Value of w1 -  [3.06201943]  and w2 -  [3.93798057]
Value of w1 -  [3.06077904]  and w2 -  [3.93922096]
Value of w1 -  [3.05956346]  and w2 -  [3.94043654]
Value of w1 - 