In [1]:
import numpy as np 

In [16]:
a = [1,2,3,4,5,6]

In [17]:
b = np.array(a)

In [5]:
type(b)

numpy.ndarray

In [10]:
b.shape

(5,)

In [7]:
c = np.ones(shape=(10))

In [8]:
type(c)

numpy.ndarray

In [9]:
c.shape

(10,)

In [11]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(shape=(10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros(shape=(10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
b

array([1, 2, 3, 4, 5, 6])

In [19]:
b.shape

(6,)

In [22]:
bb = b.reshape((2,3))

In [21]:
b

array([1, 2, 3, 4, 5, 6])

In [23]:
bb

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.random.randint(10, 30, 5)

array([13, 23, 15, 26, 29])

In [30]:
np.random.randint(100, 200, 10).reshape((5,2))

array([[182, 187],
       [186, 124],
       [102, 159],
       [167, 138],
       [192, 182]])

In [31]:
l = np.random.random((3,3))

In [32]:
l

array([[0.62314971, 0.21386247, 0.81397887],
       [0.40769165, 0.61381688, 0.70900632],
       [0.13358603, 0.29411047, 0.76363896]])

In [33]:
l.max()

0.8139788685176933

In [34]:
l.min()

0.1335860328151266

In [35]:
l.mean()

0.5080934836382305

In [36]:
l.std()

0.23719370260023473

In [37]:
a

[1, 2, 3, 4, 5, 6]

In [43]:
np.random.choice(a, size=(3))

array([2, 5, 6])

In [45]:
d = np.random.randint(9, size=(3, 4))
e = np.random.randint(10, size=(4, 5))

In [46]:
d

array([[7, 5, 3, 5],
       [8, 4, 3, 3],
       [6, 7, 3, 8]])

In [47]:
e

array([[4, 4, 6, 2, 9],
       [2, 5, 5, 3, 9],
       [5, 1, 3, 7, 3],
       [0, 9, 6, 5, 4]])

In [48]:
np.dot(d, e)

array([[ 53, 101, 106,  75, 137],
       [ 55,  82,  95,  64, 129],
       [ 53, 134, 128,  94, 158]])

In [49]:
b

array([1, 2, 3, 4, 5, 6])

In [50]:
a

[1, 2, 3, 4, 5, 6]

In [51]:
print(a * 2) 
print(b * 2)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
[ 2  4  6  8 10 12]


In [56]:
b[b >= 3]

array([3, 4, 5, 6])

In [57]:
d

array([[7, 5, 3, 5],
       [8, 4, 3, 3],
       [6, 7, 3, 8]])

In [60]:
d[(d>5) | (d<4)] 

array([7, 3, 8, 3, 3, 6, 7, 3, 8])

In [61]:
f = np.random.randint(10, 50, size=(10))

In [62]:
f

array([45, 28, 47, 17, 47, 15, 47, 20, 36, 25])

In [66]:
f <= 20

array([False, False, False,  True, False,  True, False,  True, False,
       False])

In [67]:
f[f<=20]

array([17, 15, 20])

In [68]:
f[f<=20] = 0

In [69]:
f

array([45, 28, 47,  0, 47,  0, 47,  0, 36, 25])

In [70]:
np.ceil(3.45)

4.0

In [71]:
np.floor(3.45)

3.0

In [73]:
np.round(3.4567, decimals=2)

3.46